### ISSUE TITLE
基本的なゲームシステムの構築

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#1]
# タスク

- [x] ボム関連の仕様を考える
#### ⇒ゲームシステム案5
- [x] パッケージの利用を考える
#### ⇒利用する
- [x] 2D3Dでやるかを考える

**Comment by tyanio** [comment]
# 使用するUnityのVersion
Unity 2018.3.8f1

**Comment by kugimasa** [comment]
# Review
- [ ] Kugi

- [ ] Yamakatyu

- [ ] Inahiro

- [ ] Tyanio
