### ISSUE TITLE
終了アニメーションを作る

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#100]
#73 のレビューより

- [x] 終了アニメーション案を考える

- [x] 終了アニメーション案を絞る

- [ ] 終了アニメーションを作る

**Comment by tyanio** [comment]
# 私的アニメーション案(コスト高)
![DSC_1757](https://user-images.githubusercontent.com/19584781/57782960-37eb9180-7768-11e9-967b-e21486fbff51.JPG)
![DSC_1758](https://user-images.githubusercontent.com/19584781/57782966-39b55500-7768-11e9-982e-18955d42e318.JPG)

**Comment by daigo0907** [comment]
# 終了アニメーション案（なるべくコストを抑えて）
### どこまで作っていいのか分からないので、しっくりきてないですが…

![iOS の画像 (6)](https://user-images.githubusercontent.com/40502921/60754282-02517f00-a01a-11e9-94e4-9f85c2c45ca6.jpg)
![iOS の画像 (7)](https://user-images.githubusercontent.com/40502921/60754283-054c6f80-a01a-11e9-9643-35d2ad51f422.jpg)
![iOS の画像 (8)](https://user-images.githubusercontent.com/40502921/60754285-08476000-a01a-11e9-801f-3260c3020efd.jpg)

**Comment by kugimasa** [comment]
> # 終了アニメーション案（なるべくコストを抑えて）
> ### どこまで作っていいのか分からないので、しっくりきてないですが…
> ![iOS の画像 (6)](https://user-images.githubusercontent.com/40502921/60754282-02517f00-a01a-11e9-94e4-9f85c2c45ca6.jpg)
> ![iOS の画像 (7)](https://user-images.githubusercontent.com/40502921/60754283-054c6f80-a01a-11e9-9643-35d2ad51f422.jpg)
> ![iOS の画像 (8)](https://user-images.githubusercontent.com/40502921/60754285-08476000-a01a-11e9-801f-3260c3020efd.jpg)

③好き！！

**Comment by tyanio** [comment]
めちゃ②が好きですん

**Comment by Yamakatsu63** [comment]
①が無難で分かりやすくていい！

盤上のコマが全部同じ色になってゲーム終了になったときは，②と③じゃ対応できないと思う

**Comment by iHiromu** [comment]
アニメーションを作るようになった時などのコストも考えて①派です

**Comment by TakedaHiroki** [comment]
現状②③の改善方法が思いつきません
できるようであればゲーム的に③だけどとりあえず①なのかなあ

**Comment by daigo0907** [comment]
意見ありがとうございます
もう少し案を考えます

- キーアイテムをどちらが獲ったのか

- 勝利パターンに応じたもの

- 自分の勝敗を分かりやすく

- コストは抑えたい

この辺を踏まえて、考える

終了アニメーションとリザルト画面の役割を考える

**Comment by daigo0907** [comment]
# 終了アニメーション案その２
新しく考えました！
***
終了アニメーションを３つ
それとは別に、勝敗の表示の仕方を４種類考えました
終了アニメーションと勝敗表示を上手く組み合わせたいと思ってます
***
終了アニメーションは前回の①をベースにしています。
***
## 終了アニメーション案
![iOS の画像 (9)](https://user-images.githubusercontent.com/40502921/61192584-58948100-a6f0-11e9-9125-54491303c0e9.jpg)
![iOS の画像 (10)](https://user-images.githubusercontent.com/40502921/61192564-3864c200-a6f0-11e9-9891-684c68027ae0.jpg)
***
## 勝敗表示
![iOS の画像 (11)](https://user-images.githubusercontent.com/40502921/61192572-4286c080-a6f0-11e9-8757-8c92ef83e81a.jpg)
![iOS の画像 (12)](https://user-images.githubusercontent.com/40502921/61192578-4a466500-a6f0-11e9-9e15-fdb1e7442e4f.jpg)
![iOS の画像 (13)](https://user-images.githubusercontent.com/40502921/61192579-4f0b1900-a6f0-11e9-9565-ef036bce5008.jpg)
![iOS の画像 (14)](https://user-images.githubusercontent.com/40502921/61192580-54686380-a6f0-11e9-8361-9f3f7cab36c2.jpg)
***

**Comment by daigo0907** [comment]
ごちゃごちゃしていて見難いです。。。
コメントしてもらえたら、大変助かります

**Comment by kugimasa** [comment]
終了アニメーションについては①が良いかなーと思いました！
自分のコマがキーアイテムとって負けたときに自分のコマ達が倒れるのはそれで面白いかも笑

勝敗表示はあったほうが良いと思いました！(リザルトシーンでも表示するにしても)
案で言うとb,cが好きです

**Comment by iHiromu** [comment]
終了アニメーションは1か3がいいと思います！
1で全部動いてごちゃごちゃするなら3かなって感じで

勝敗表示はcがいいと思いました！
アニメーションも見えそうだから

**Comment by Yamakatsu63** [comment]
終了アニメーションは①がいいと思います！

勝敗結果は②がわかりやすくていいと思います！

**Comment by TakedaHiroki** [comment]
1が意図してることと近いと思うのでわかりやすくていいと思います
