### ISSUE TITLE
黒駒の目のテクスチャを付ける

### ISSUE THREAD

**Issue by iHiromu** [cammelworks/doubleEdged#101]
- [x] UV展開をする

- [x] Gimpでのテクスチャ作成する

- [ ] Unityへインポートする

**Comment by tyanio** [comment]
ちゃんとやり方をまとめてくれてありがとう！

その上でなんやけどちゃんとは言ってなかったかもしれんけど一番上のコメントには「やること」をチェックボックスで箇条書きしていってその下のコメントに「どうやってやったか」を書いていってほしい、他のIssueとおんなじよ

まあ分からんかったら聞いておくれ
しかし例えばチェックボックスの作り方が分からんかったら「Git Issue チェックボックス」とかで調べたら絶対に出てくるからまず調べることから練習してみてくれ

**Comment by tyanio** [comment]
ちなみに優先度に関してはそこまで高くないのでだれかがSlackかもしくはこのIssueに返信しないようなら放置で構わんよ
他のことをしておくれ

**Comment by iHiromu** [comment]
1. blenderからコマのテクスチャを貼りたい部分のメッシュ構造を破壊しないためにシームをつける
2. 残りのUV展開をする部分を選択しUV展開をする
3. 展開図の調整
　a. 展開したものの元が曲線であったりする場合、そのままテクスチャを貼り付けたら歪んでしまったりするので調整が必要であれば調整（今回は必要がないのでやってません）
4. UV展開されたものをエクスポートする
5. Gimpよりテクスチャの作成をする
　a. Gimpにエクスポートした画像をインポートする
　b. 新しくレイヤーを作成しインポートした画像に合うように目を作成する(閉じた時と、倒れた時を作成)
　c. 作成したレイヤーを残し画像をエクスポートする

6. unityへ

参考サイト
・https://www.cgradproject.com/archives/2425/
・https://ameblo.jp/kay-nea/entry-12423573598.html

**Comment by kugimasa** [comment]
invalidタグ(This doesn't seem right. : 何かがおかしい)をつけました
