### ISSUE TITLE
砲撃システムを使えるようにする

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#105]
- [x] 砲撃範囲を修正する

- [x] script内の変数名を変更する(radar -> fire)
- [x] itemButtonの内容をfireButtonに変更する

- [x] 砲撃可能なBoxにLockOnMarkerをつける

- [x] リファクタを終える

**Comment by Yamakatsu63** [comment]
## LockOnMarkerの表示・非表示の切り替え

LockOnMarkerのオブジェクトのsetActive()で表示の切り替えをすると，表示したときにカクカク動くようになるので，Imageコンポーネントのenableプロパティで切り替えるようにする．

**Comment by Yamakatsu63** [comment]
## LockOnMarkerの実装

- あらかじめGameSceneにLockOnMarkerを４つ配置 (初期状態ではImageコンポーネントのenabledはfalse)．
- doubleEdgedSystem.csで4つのLockOnMarkerをゲームオブジェクトの配列として管理 (LockOnMarkerの配列の添え字はBoxesLocationListの添え字と対応)
- CanUseFire()でFire可能なBoxが見つかり次第，そのBoxに対応したLockOnMarkerのImageコンポーネントのenabledをtureにする．
- ターン終了時にすべてのLockOnMarkerのImageコンポーネントのenabledをfalseにする．
- BoxがFireされるとLockOnMarkerのターゲットがなくなるため，表示されなくなる．
