### ISSUE TITLE
BOXの位置が正しい位置にくるようにする

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#106]
- [x] BOXのモデルを作成する

- [x] BOXのテクスチャを作成する

- [x] BOXを8x8の盤サイズに調整する

**Comment by kugimasa** [comment]
## モデルとテクスチャ(暫定)を作成しました
テクスチャの方はフリー素材を貼り付けただけなので, もう少し凝りたいです.
今後Daigoくんにテクスチャの方お願いするかもです
![スクリーンショット 2019-05-20 10 49 11](https://user-images.githubusercontent.com/40158101/57992092-601f1b80-7aed-11e9-95e3-d7b837eff87e.png)

**Comment by Yamakatsu63** [comment]
## モデルをリサイズして配置するようにしました
盤の色と近いからちょっと見にくいかも
![boxTest](https://user-images.githubusercontent.com/40345570/58232766-56a7e480-7d75-11e9-8283-1f6767c9fb12.png)

**Comment by kugimasa** [comment]
テクスチャとりあえずはこれで問題ない気がします
