### ISSUE TITLE
リファクタリングをする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#118]
# 現在の状況

- [x] BoardScriptをリファクタリングする

  - [x] OthelloSystem：普通のオセロのシステムをつかさどるクラス

  - [x] OthelloGameManager：ゲームの進行をつかさどるクラス(このままゲームのマネージさせるならOthello外したい、しかしGameManagerっていう名前のScriptは使えない？**いい名前募集中**)

  - [x] DisplayObject：実際にオブジェクトを作ったり位置の調整をしているクラス

  - [x] DoubleEdgedSystem：ダブルエッジで追加されているシステムをつかさどるクラス

- [x] CellScriptをリファクタリングする
  
  - [x] Cell：旧CellScript
　
- [x] PieceScriptをリファクタリングする

  - [x] Piece：旧PieceScript
　
- [x] Item：BombやKeyitemにつけるスクリプト

- [x] 元あった機能の復旧をする
 
  - [x] UIAudio関連の復旧をする

  - [x] アニメーション関連の復旧をする

  - [x] シーン遷移を復旧する

  - [x] GameSEをつける

  - [x] Scoreを表示する

**Comment by tyanio** [comment]
# スクリプトのファイル名
インスペクターでスクリプトは(Script)と表示してくれるし重複するのも面倒なのでScriptはつけません！
クラスの名前でその機能が分かる感じでお願いします！

**Comment by tyanio** [comment]
# 変数のprivate宣言
privateはデフォルトの変数宣言なので以降は書かないこととします!

**Comment by kugimasa** [comment]
> # 変数のprivate宣言
> privateはデフォルトの変数宣言なので以降は書かないこととします!

どのように宣言すれば良いですか??

**Comment by tyanio** [comment]
# クラス名は大文字始まりで
# ゲームオブジェクト名も大文字始まり
# インスタンスしたクラスは小文字始まりで

**Comment by tyanio** [comment]
#GetComponent<Script>()でスクリプトファイルがとってこれない
助けて

**Comment by tyanio** [comment]
# 位置情報は基本的には二次元ベクトルで

**Comment by tyanio** [comment]
# 業務エラー処理・例外処理について
想定できるエラーに対してはフローを付け加えてあげて表示とか
例外処理についてもちょっと勉強したいです！
返り値とかも有効活用したい
https://blogs.msdn.microsoft.com/nakama/2008/12/29/net-part-1/

**Comment by tyanio** [comment]
# MonoBehaviorとUnity開発におけるクラスの継承について
MonoBehaviorは”Start()”とか”Update()”とかその他もろもろのメソッド、フィールドを定義してるクラスです( https://docs.unity3d.com/ja/current/ScriptReference/MonoBehaviour.html )
そしてC#は”(新クラス名) : (継承元クラス名)”でクラスの継承をしています
今のプロジェクトを触ったことがある人にはわかると思いますが基本的にUnityは○○ : MonoBehaviorとなっていてこれはUnityにあるMonoBehaviorをすでに継承してるのがほとんどなのです
MonoBehaviorを使いたくない場合に満たさないといけない条件は**Hierarchy上に実体がない**のと**Awake, Start, UpdateといったUnityが自動で実行するメソッドが必要ない**と、なかなかに厳しいです
C#は多重継承を許さないのでこの場合ヒエラルキーに存在するようなGameObjectについているスクリプトはほかのクラスの継承はできません…
---
##対策(スクリプトを何個も用意するのも場合分けでメソッドがバカ長くなるのも避けたい)考え中…

**Comment by tyanio** [comment]
# Audio関連
AudioManagerに今一応まとめております
正直まとめる必要はあまりないかもしれないけど個人的にはだいぶ見やすい
利点としては
- AudioClipのInspectorからの指定が一回で済むようにできてる
- メソッドはManagerクラスで常にObjectとして存在してるので取得できればどこからでも呼べる(正直StaticClass,StaticMethodにしたほうがいいかも)

# Scene遷移関連
これもSceneController(Managerにしたかったけど公式クラスとしてあったから使えなかった)で一括管理してます
これが一番要らんかも、今のところ一行メソッドしかない
ただロードシーンとか実装するならここで作るとかなりいいかも

# Advertisement関連
これもAdvertisementManagerで管理してます、機能を分けただけなので特にいうことなし

#そしてButton
先の三つのクラスを適宜OnClick()に呼ぶだけで済むようになりました、すっきり！

リファクタしたい！！

**Comment by kugimasa** [comment]
# Animation関連
Animatior を Pieceスクリプトで宣言して, Animatorの管理Pieceスクリプト内で行います

**Comment by tyanio** [comment]
https://qiita.com/k7a/items/df6dd8ea66cbc5a1e21d
