### ISSUE TITLE
新しいロゴ用のアイコンを作成する

### ISSUE THREAD

**Issue by daigofuji0907** [cammelworks/doubleEdged#119]
#88 参照

- [x] アイコン案を考える

- [x] アイコンサイズに入れ込む

- [x] 成果物として共有する

**Comment by daigo0907** [comment]
こんな感じのアイコンにしました！
![DoubleEdged_NewIcon1028](https://user-images.githubusercontent.com/40502921/60404570-1560eb00-9be5-11e9-86c2-64e80499d24c.png)
