### ISSUE TITLE
大砲をゲームに導入する

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#121]
- [x] ~大砲のモデリングをする~

- [x] 新しいコンセプトに沿った大砲のモデリングをする

- [x] 大砲のリギングをする

- [x] 大砲と[砲撃システム](https://github.com/cammelworks/doubleEdged/issues/105) を結びつける

**Comment by kugimasa** [comment]
参考画像
![大砲１](https://user-images.githubusercontent.com/40158101/59193080-86514c00-8bbf-11e9-94ea-f64c09eecd9c.png)

**Comment by kugimasa** [comment]
リモデリングをお願いしたので一度チェック外します
🙇‍♂️

**Comment by tyanio** [comment]
Issueのコメントでも使わなくなった機能とか新しく追加する機能があれば、できれば書き直すのではなくて新しくコメントで追加してあげよう
やったことはやったことやし、それが変更になったこと、それで新しくIssueが増えたということが分かりやすく見えるので(一応変更履歴で見れるっちゃ見れるけど)

**Comment by kugimasa** [comment]
アニメーションはついてます
玉は飛びません
