### ISSUE TITLE
!ゲームシーンのコンセプトアートを募集します!

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#122]
PO(Tyanio)から依頼がありました！
みなさんの思うゲームシーンのコンセプトアートを自由に描いて(文章でも可です！)このIssueに投稿してください！
フォームは問いません 👍

**Comment by tyanio** [comment]
個人的にしっくり来てるわけでもないけど一応
![DSC_0777](https://user-images.githubusercontent.com/19584781/59294379-5471df80-8cbc-11e9-8b60-92f9d9331165.JPG)
![DSC_0778](https://user-images.githubusercontent.com/19584781/59294383-56d43980-8cbc-11e9-99f4-382d35e1d7a7.JPG)
![DSC_0779](https://user-images.githubusercontent.com/19584781/59294388-58056680-8cbc-11e9-9a52-ecd4540abbef.JPG)
大砲の時代錯誤感は割と気になってはいます、あとは自分のToon感というか在庫がないのでいい案を募集したいのであります

**Comment by kugimasa** [comment]
# 設定
## おもちゃ箱案
おもちゃの兵隊たちが夜な夜な遊びで戦っている 

## 遺跡？探索案
謎の箱が沢山積み重なった世界
箱の中には爆弾もしくはキーアイテム(大事な資源が入っている)
ShiroとKuroたちは戦い(オセロ)で陣地を拡大させながら, キーアイテムを取り合っている.

キーアイテムの重要性について考えてみた.
今までのゲーム案では, オセロの勝敗のみに焦点を置いていた.
そこでこのゲーム内での報酬を以下にする
* キーアイテムを取った個数
* 陣地の割合(オセロの勝敗)

**Comment by Yamakatsu63** [comment]
## コロシアム案
- 相手と自分の陣地に1回だけ撃てる大砲を設置
- 盤をコロシアム風に
- 盤を浮かせるような背景

**Comment by tyanio** [comment]
![DSC_1853](https://user-images.githubusercontent.com/19584781/59404900-67330400-8de3-11e9-9ef3-6458f933f07c.JPG)

**Comment by daigofuji0907** [comment]
# 陣取り合戦！！

![iOS の画像](https://user-images.githubusercontent.com/49432948/59404956-a19ca100-8de3-11e9-89c6-eaba6c1f2af3.jpg)

時代は、、、飛行機や飛空艇がでてくる程度がいいのかな
キーアイテムを取った状況で仲間が迎えに来るみたいな。。。

**Comment by iHiromu** [comment]
# ゲーム時代背景
大砲、ヘルメット、銃のようなアイテムから
国同士(煉瓦造りのような建物のある国)のキーアイテムを取る争い
-なんとなくハリポタみたいな建物？

**Comment by kugimasa** [comment]
# 共通認識できた！
