### ISSUE TITLE
決まったコンセプトに沿うデザインを考える

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#127]
- [x] キーアイテムを考える

- [x] 盤まわりを考える

**Comment by kugimasa** [comment]
![iOS の画像 (1)](https://user-images.githubusercontent.com/40158101/59889566-ec33a400-9407-11e9-84a9-bd9f2df07556.jpg)
![iOS の画像 (2)](https://user-images.githubusercontent.com/40158101/59889570-ef2e9480-9407-11e9-9ff5-d05dcb65a025.jpg)
![iOS の画像](https://user-images.githubusercontent.com/40158101/59889581-fe154700-9407-11e9-98df-75d3b4274e04.jpg)
![side](https://user-images.githubusercontent.com/40158101/59889584-0077a100-9408-11e9-8428-ecefcb0c22f5.jpg)

**Comment by daigofuji0907** [comment]
最終的には
- キーアイテムは、鉱物の原石
- 盤回りは、上の仕様書の通りです
![クリスタル１](https://user-images.githubusercontent.com/49432948/60245833-61b3de80-98f8-11e9-8cc1-554ed3db72ce.jpg)
