### ISSUE TITLE
決まったコンセプトに沿った盤を導入する

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#128]
#127 デザイン案はこちらを参照！

- [x] 地面をつくる

- [x] 箱をつくる

- [x] 線路をつくる

- [x]  トロッコ

- [x] 大砲をつくる

- [x] Unityへできたモデルをインポートする

※適宜追加、削除をお願いします

**Comment by kugimasa** [comment]
仕様書です！
![iOS の画像](https://user-images.githubusercontent.com/40158101/59573255-08c09b00-90ed-11e9-9466-d7f4077490d8.jpg)

**Comment by iHiromu** [comment]
多分これで線路を作れる
https://www.youtube.com/watch?v=EFVsK3GYOdc

**Comment by kugimasa** [comment]
![スクリーンショット 2019-06-30 11 57 12（2）](https://user-images.githubusercontent.com/40158101/60391687-264f2500-9b2f-11e9-8830-a88070a3f864.png)
ひとまず砲台以外

**Comment by kugimasa** [comment]
砲台もインポートできました！
![スクリーンショット 2019-07-01 9 43 33](https://user-images.githubusercontent.com/40158101/60404597-72f53780-9be5-11e9-8f51-3837a6c51a4a.png)
