### ISSUE TITLE
リリースの準備をする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#13]
- [x] GooglePlayのデジタル証明がされたパッケージファイルについて詳しくまとめる

- [x] GooglePlayの申請の長さをまとめる

- [x] AppStoreのデジタル証明がされたパッケージファイルについて詳しくまとめる

- [x] Appstoreの申請の長さをまとめる

**Comment by iHiromu** [comment]
アプリの申請期間(参考サイト)
https://jokapi.jp/column/app_judge/
・GoogleStore早くて数時間
機械で審査、公序良俗に反していなかったり、マルウェア(悪意のもの開発・利用されるソフトウェア)が仕込まれていなかったりすればOK
・Appstoreの方が厳しく1~3日(もっとかかる場合もある)
ガイドラインに沿っていればスムーズにいくかも？
Appstoreのガイドラインhttps://developer.apple.com/jp/app-store/review/guidelines/

**Comment by iHiromu** [comment]
・iosのデジタル証明発行
Provisioning Profileを作成して証明書ができる
Provisioning Profileの作成について：https://joyplot.com/documents/2016/10/29/ios-provisioning-profile/
アプリの公開の流れ：https://qiita.com/nirasan/items/28e0947002fc3e1b7a65
・androidのデジタル証明発行
Unityのbuildの際に証明書付きのAPKが作成できる
証明書付きAPKの作成：https://tech.pjin.jp/blog/2016/04/01/unity_googleplay_apk_build/
アプリの署名について：https://developer.android.com/studio/publish/app-signing?hl=ja

**Comment by iHiromu** [comment]
- [ ] tyanio

- [ ] kugi

- [ ] yamakatyu
