### ISSUE TITLE
カメラ視点が移動できることを分かりやすく伝える

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#131]
- [ ] 実装の仕方を考える

- [ ] カメラ視点のチュートリアルを実装する

- [ ] カメラを使えることをわからせるアニメーション・画像を実装する

**Comment by daigofuji0907** [comment]
6/21(金)のデイリースクラムにて少し話しました
![iOS の画像 (4)](https://user-images.githubusercontent.com/49432948/59889841-3f5a2680-9409-11e9-940b-4cd602f2a544.jpg)
