### ISSUE TITLE
決まったコンセプトに沿ったスカイボックス(背景)を作る

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#134]
- [x] Asset Storeで無料の良さげなスカイボックスを見つける

- [x] スカイボックス Front[+Z]

- [x] スカイボックス Back[-Z]

- [x] スカイボックス Left[+X]

- [x] スカイボックス Right[-X]

- [x] スカイボックス Up[+Y]

- [x] スカイボックス Down[-Y]

**Comment by kugimasa** [comment]
[スカイボックスについて](https://docs.unity3d.com/ja/current/Manual/class-Skybox.html)
[スカイボックスの作り方](https://docs.unity3d.com/ja/current/Manual/HOWTO-UseSkybox.html)
[自作スカイボックス](https://qiita.com/aike@github/items/cf4a8289fef65c9652a7)
[Asset Storeで落とすもあり](http://inter-high-blog.unity3d.jp/2017/07/06/skybox/)

**Comment by daigo0907** [comment]
skybox 入れました！
