### ISSUE TITLE
チュートリアル説明文をまとめる

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#14]
- [x] 普通のオセロの説明文をまとめる

- [x] DoubleEdgedの各アイテムの説明文をまとめる

- [x] DoubleEdgedのゲーム進行の説明文をまとめる

**Comment by iHiromu** [comment]
ざっくりと載せた方が良さそうな説明をまとめてみた。もう少しゲームができていって載せるべき内容がわかってきたら追加で考えていこうと思う。
駒の置き方
レーダーの使い方
キーアイテムとボムについて
サレンダについて
レート、ランキングについて

**Comment by iHiromu** [comment]
- [ ] tyanio
- [ ] kugi
- [ ] yamakatyu

**Comment by tyanio** [comment]
# できたチュートリアル文・画像
https://1drv.ms/p/s!ApsHvSVcOMJ5h9otHwEE6O1bcY37Qg
