### ISSUE TITLE
新しくできたロゴ・アイコンをインポートする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#152]
- [x] ロゴをインポートする

- [x] アイコンをインポートする

- [x] ビルドして確認する

**Comment by kugimasa** [comment]
# ロゴ
![IMG_0010](https://user-images.githubusercontent.com/40158101/60681647-0b800600-9ecb-11e9-9ecc-2b4ea5977e9c.jpg)
# アイコン
![IMG_0DCE03841B80-1](https://user-images.githubusercontent.com/40158101/60681650-0e7af680-9ecb-11e9-89f6-74116f03ed21.jpeg)

**Comment by kugimasa** [comment]
Androidの確認はまだです.

**Comment by kugimasa** [comment]
Androidでも確認できました！
