### ISSUE TITLE
マテリアルのバグを直す

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#153]
- [ ] Cellのバグを直す(Androidのみ確認済み)

- [x] 黒大砲の白光りを直す

- [x] コマの白光りを直す

**Comment by kugimasa** [comment]
光源を消して見ましたが, コマのヘルメットの反射と大砲の反射は残っていました...

**Comment by kugimasa** [comment]
色々調べてみましたが, UnityのGameViewの見え方とiOS, Android実機の見え方が異なる理由はわかりませんでした. 調べた上で考えられる原因としまして
* Build Settings で指定されているios用のシェーダー, Android用のシェーダーがUnity上でレンダリングする際機能していない
* Unityで実行する際処理を軽くするために反射などは最小限になっている
などが挙げられますが, 本当の理由はわかりません

iosのシェーダーとAndroidのシェーダーが異なるということはわかりました.

妥協案として, Cannon MaterialのMetalic値(値が大きい場合周囲からの光を強く反射します), Smoothness(値が大きいと鏡面反射の方向のばらつきが少なくなります)を共に0.0にして拡散反射のみで表現を行なっています. 
ios実機での確認は取れました.

![IMG_AAC5067488BA-1](https://user-images.githubusercontent.com/40158101/60681537-9b718000-9eca-11e9-87b1-56b541ecc090.jpeg)

*Standard Shaderのパラメーターについて*
https://docs.unity3d.com/ja/current/Manual/StandardShaderMaterialParameterMetallic.html
https://docs.unity3d.com/ja/current/Manual/StandardShaderMaterialParameterSmoothness.html
