### ISSUE TITLE
サレンダーボタンの改良案を用意する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#162]
- [x] 分かりやすいサレンダーボタン案を考える

- [x] サレンダーボタンを押した際確認させるようにする案を考える

- [x] サレンダーボタンアイコンを用意する

**Comment by daigo0907** [comment]
# サレンダーボタン案です
![iOS の画像 (15)](https://user-images.githubusercontent.com/40502921/61286362-a21ec200-a7fd-11e9-9d62-c789f2932cb5.jpg)

**Comment by tyanio** [comment]
良いと思うんやけど、真ん中の画面は二度手間じゃない？と思った

**Comment by tyanio** [comment]
![SurrenderFlag](https://user-images.githubusercontent.com/19584781/61709761-e3c5e480-ad8a-11e9-87f6-7ad1336b0cdf.png)
