### ISSUE TITLE
相手が直前に置いたマスを分かるようにする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#166]
- [ ] ヴィジュアル案を考える

- [ ] 実装する

**Comment by daigo0907** [comment]
いくつかオセロアプリで遊んでみて確認しました！
基本的にどのアプリでも「相手が直前に置いたマス」は分かる使用になっていました。
共通して見られたのは
- 同心円状のエフェクト

- 中心に点or丸

- 赤色を使っている
こんな感じでした
