### ISSUE TITLE
盤のモデルを改良する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#173]
- [x] 盤の端の違和感を無くす方法を考える

- [x] 実装する

**Comment by daigo0907** [comment]
# 盤の端が途切れている問題
現状の違和感
***
## 改善策
全体的に拡大する
崖を伸ばしていく
ある程度の距離で海を作成
崖で覆う

**Comment by daigo0907** [comment]
## unity上だとこんな感じになりました
![iOS の画像](https://user-images.githubusercontent.com/40502921/60889734-ad6d6d00-a294-11e9-976a-06205f55f2f4.png)
![iOS の画像 (1)](https://user-images.githubusercontent.com/40502921/60889736-afcfc700-a294-11e9-8bde-fdec21063afc.png)

***

海の色がはっきりしすぎなので、すこし違和感がある
水のテクスチャを入れるかも？

**Comment by kugimasa** [comment]
masterにマージしてます
