### ISSUE TITLE
報酬アイテムを考える

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#175]
- [x] ガチャシステム案を挙げる

- [ ] アイテムのテーマを考える

- [ ] テーマ案を描く

**Comment by daigo0907** [comment]
## 報酬アイテムについて考えてみる
キーアイテムを集めて何が報酬として交換できるか

- 大砲の着せ替え

- キャラの着せ替え

- プレイヤーのエムブレム

- 自陣の旗

- キャラの強化

- 補助アイテムの獲得

など

**Comment by daigo0907** [comment]
## こんなのどうですか
### ガチャシステム

- 大砲の着せ替え

- キャラの着せ替え

- 自陣の旗

上記３種が１つのガチャから排出される
キーアイテムを多く払うことで１種に固定されたガチャも回せる
同じシリーズをすべてそろえることで、エムブレム獲得
とか

***
### 対戦補助アイテム
対戦前に使用することで有利に進められる
キーアイテムを払って購入する
ex)

- 既に砲撃され見えないボックスを見えるようにするアイテム

- 砲撃が２回使用できるアイテム

- 自分のターンの制限時間を少し伸ばすアイテム

- １度だけボムを踏んでも無効化できるアイテム

- 自分が補助アイテムを使っていることを隠すアイテム
など

**Comment by daigo0907** [comment]
## ガチャアイテムのテーマ
木造、鉄、銅、クリスタル、
メカ、ナイト、パイレーツ、バイキング、
恐竜、海底、火山、
など
いろんなゲームから調べてみるとよいかも…
### 対戦相手と同じテーマもしくは同系色のテーマになるとまずい
どっちがどっちかわからない
- 黒バージョン白バージョンを用意する
- 各マスにも色がつくようにする
とか
