### ISSUE TITLE
アカウント登録ができる

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#192]
# 15thSprintのデバッグ
- 名前変更を二回するとPlaceHolderが機能してない(一回目に変わったユーザー名が実体として残ってるので入力するときに消さないといけない)
***
# 13thSprint
全員が匿名アカウントログインしてユーザー名の変更ができたらゴール！

> 参考画像
![iOS の画像 (2)](https://user-images.githubusercontent.com/19584781/68939181-4c761880-07e3-11ea-8a67-e69ecf561231.jpg)
---
新しく追加したSignInシーンからテストデータ
- ユーザー名：テスト
- (メールアドレス)：aaa@amail.com
- Password：aaa
でアカウントを登録して、タイトルにユーザー名をフィードバック！

サインアップ・ログインのエラーはフィードバッグして、さらに2重ログインは防ぐ！

**Comment by kugimasa** [comment]
タイトルシーンにてメールアドレスのフィードバック達成されました。
* ログインしていない状態では"Guest"と表示されます
* ログインしている場合はメールアドレスが表示されます

**問題点**
* 複数端末を使うことで、同じアカウントに対して同時にログインすることができてしまいます

**Comment by kugimasa** [comment]
サインイン・ログイン時のエラーのフィードバック
- [x] 入力フォームに空欄がある場合エラー
- [ ] Firebaseに登録できなかった場合エラー

**Comment by Yamakatsu63** [comment]
FirebaseAuthのエラー一覧は[こちら](https://firebase.google.com/docs/reference/unity/namespace/firebase/auth)で確認できます

実装している例外処理
- EmailAlreadyInUse
- InvalidEmail
- WeakPassword
- WrongPassword

**Comment by kugimasa** [comment]
PO(@tyanio )からの承諾をいただいたのでCloseしまーす！

**Comment by Yamakatsu63** [comment]
匿名ログインの方法
https://firebase.google.com/docs/auth/unity/anonymous-auth

**Comment by kugimasa** [comment]
> 匿名ログインの方法
> https://firebase.google.com/docs/auth/unity/anonymous-auth

**Comment by kugimasa** [comment]
*バグ*

- [ ]  文字数を制限する
- [ ] ユーザ名の書式を制限する
- [ ] プレイスホルダーにユーザ名を表示する

**Comment by tyanio** [comment]
# バグ
名前変更を二回するとPlaceHolderが機能してない(一回目に変わったユーザー名が実体として残ってる)
