### ISSUE TITLE
広告の仕方について調べる

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#2]
# タスク
- [x] LINEとの連携(招待機能など)を調べる
- [x] Twitterとの連携(同上)を調べる

**Comment by tyanio** [comment]
- [ ] Tyanio

- [ ] Kugi

- [ ] Yamakatyu

**Comment by iHiromu** [comment]
１
sociel-connectorをダウンロードする、Unityプロジェクトにインポートする。
コードはurlにappstoreのリンクを貼って、ボタン等の実装はunityでお願い
http://unity-yuji.xyz/twitter-only-share-button/ 
(このページだとTwitterのシェアになってるけど同じようにLINEも多分できると思う...)
https://www.clrmemory.com/unity/socialconnector-twitter-line/

２
・文字のみでの投稿になる、Application.OpenURLっていう簡単なコードでできるらしい。
http://takashicompany.hatenablog.com/entry/2014/06/19/031810
http://westhillapps.blog.jp/archives/37740489.html

3
言語がSwift、JavaだからC#との互換性とかがよくわからないところ...
このページが画像とかあって一番イメージとかがわかりやすかったから一応載せておく
http://ginkgo.hateblo.jp/entry/2017/11/18/131738

**Comment by iHiromu** [comment]
- [ ] tyanio
- [ ] kugi
- [ ] yamakatyu
