### ISSUE TITLE
対戦履歴が確認できる

### ISSUE THREAD

**Issue by Yamakatsu63** [cammelworks/doubleEdged#200]
アカウントの
- 対戦回数
- 勝利回数

をタイトルの別パネルで表示して確認出来たらゴールです！

**Comment by tyanio** [comment]
てすと

**Comment by kugimasa** [comment]
Systemの実装は完了しています。

**Comment by kugimasa** [comment]
UIの設計 → @kugimasa
UIのアセット制作 → @daigo0907 @iHiromu 
UIの実装 → Systemチームの誰か

**Comment by kugimasa** [comment]
![スクリーンショット 2019-11-28 22 28 43](https://user-images.githubusercontent.com/40158101/69810262-d89a2e00-122e-11ea-993c-9b1679c80960.png)
UI実装しました

Kuroコマの画像はUserImageとしてとりあえず置いてます。

あと、ホームシーンのユーザ名の表示ですが、正直いらない気もします。
アカウントページで確認できるようになったので、

**Comment by kugimasa** [comment]
![スクリーンショット 2019-11-30 22 59 59](https://user-images.githubusercontent.com/40158101/69901460-31033400-13c5-11ea-82a4-91fdc4552e8c.png)
対戦回数の実装しました！

**Comment by kugimasa** [comment]
チュートリアル時にもデータがPUSHされてしまうので、分岐処理が必要です！

**Comment by Yamakatsu63** [comment]
チュートリアルの結果がデータベースにPUSHされないように条件武器を追加しました

**Comment by kugimasa** [comment]
# バグ
* チュートリアルのサレンダーを押すと、負けカウントになる
#31 
---
