### ISSUE TITLE
全体のコンセプトアートを描く

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#203]
# ゴール！
すべてのSceneの設計書を見せられるのがゴール！

**Comment by tyanio** [comment]
# フォント
ラノベPOPを使います
http://www.fontna.com/blog/1706/

**Comment by tyanio** [comment]
# タイトル
![DSC_1944](https://user-images.githubusercontent.com/19584781/68362528-ec400080-016a-11ea-8ae6-bfeb4e46cbed.JPG)

**Comment by tyanio** [comment]
# ボタン
ボタンについては基本的にはAssetStoreから
シンプルで、さほどこだわらなくてもよい
立体感は大事

**Comment by tyanio** [comment]
# フィールド
ビッグサンダーマウンテンみたいな？

**Comment by tyanio** [comment]
# 砲撃システム
砲撃システムは大砲をなくして普通にボタンで木箱の中身を確認できるだけにする

**Comment by tyanio** [comment]
# コマ
![iOS の画像](https://user-images.githubusercontent.com/19584781/68363914-b8b3a500-016f-11ea-9392-a4d2db240fa1.jpg)
色は白黒

**Comment by tyanio** [comment]
# ウインドウ
![IMG_20191107_152524](https://user-images.githubusercontent.com/19584781/68365027-ec43fe80-0172-11ea-9d82-c90c2595cef0.jpg)

**Comment by tyanio** [comment]
# 2D素材
- カメラリセット
- 旧砲撃ボタン

**Comment by tyanio** [comment]
てすと

**Comment by tyanio** [comment]
# BGM・SE
BGMは戦闘のやつ変えたいかも
SEはつるはしとかモデルのかわったところに対応する

**Comment by tyanio** [comment]
# フィールドモデル
案
![DSC_1950](https://user-images.githubusercontent.com/19584781/68565365-a189f580-0496-11ea-81ed-160a99aad2fb.JPG)
盆地でこれが一面ぐるっとある感じ
![DSC_1949](https://user-images.githubusercontent.com/19584781/68565366-a189f580-0496-11ea-94aa-9b3ff1adcfac.JPG)

**Comment by daigo0907** [comment]
# UIの配置
案（ちょっと汚いですが）
![iOS の画像](https://user-images.githubusercontent.com/40502921/68587135-a9af5880-04c9-11ea-9168-891fc3ba314f.jpg)

**Comment by daigo0907** [comment]
# ゲーム背景
イメージ
炭鉱夫たちの仕事合間の遊び
白黒のチームに分かれ、陣地を取り合う
戦いではない、平和的な賭け事
