### ISSUE TITLE
コマモデル

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#208]
# タスク
* マテリアル(トゥーンシェーダー)

**Comment by kugimasa** [comment]
ピッケル制作は完了しています。
白コマについては頭の弾丸を、黒コマについては腰のポーチを取り除きます

**Comment by kugimasa** [comment]
デバッグ用のGraphics Sceneを作成しました
今後調整などはGraphics Sceneで行い、GameSceneへインポートしたいと思います

**Comment by kugimasa** [comment]
ピッケルのテクスチャは全部統一で行きます

**Comment by kugimasa** [comment]
Graphics SceneのコマはPrefab(GameSceneのもの)の1/4スケールです

**Comment by kugimasa** [comment]
# イメージ
![4B2E1CF1-7DD3-4C96-886E-D2997B458AF3](https://user-images.githubusercontent.com/40158101/70842580-dbb92f00-1e68-11ea-9259-489db8ee39a0.jpeg)

**Comment by kugimasa** [comment]
## 方針

- ToonShader : RampTextureをインスペクターから入力できるように
- OutlineShader : 2Passで実装されているものを利用

[こちら](http://nn-hokuson.hatenablog.com/entry/2018/02/06/200116)のToon＆Outlineを[こちら](http://nn-hokuson.hatenablog.com/entry/2017/03/27/204255)のToonに差し替え

**Comment by kugimasa** [comment]
## iOS 実機でのスクショ比較

![4434BCC2-829E-4BAF-BC16-58F22957CFA1](https://user-images.githubusercontent.com/40158101/71227225-d0ab4680-2321-11ea-962d-0d0e9c5c7dfd.jpeg)
![2AADB37C-BF57-42ED-BC91-FC84ACD0EBDA](https://user-images.githubusercontent.com/40158101/71227226-d0ab4680-2321-11ea-97be-00f00adbf808.jpeg)
![A5515ECD-17AB-4F3A-ADEC-F8002A488D23](https://user-images.githubusercontent.com/40158101/71227227-d0ab4680-2321-11ea-8b63-28604ffcc4c3.jpeg)

**Comment by kugimasa** [comment]
## 16th Sprint TODO
- [ ] Shiroコマの頭のテカリなくす

**Comment by kugimasa** [comment]
テカリません...!!
![スクリーンショット 2019-12-25 21 22 04](https://user-images.githubusercontent.com/40158101/71446199-0908b580-2764-11ea-8a03-26df01327305.png)
