### ISSUE TITLE
MININGシステムが使える

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#216]
# ゴール
## 仕様
* 特殊アイテム
   -  BOMB(3個)
   - KEYITEM(1個)
 * 盤
   - 8 × 8

現行のUIを削除してください

## 手順
* CPUにMININGシステムを実装
* オンラインに組み込みます

---

**Comment by Yamakatsu63** [comment]
CPU対戦がMININGシステムに対応しました。
