### ISSUE TITLE
アニメーションを考える

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#23]
- [x] 待機アニメーションを考える

- [x] 挟んだ時のアニメーションを考える

- [x] 挟また時のアニメーションを考える

- [x] コマ出現のアニメーションを考える

- [x] ゲーム終了時のアニメーションを考える

- [x] レーダー使用時のアニメーションを考える
 =>選択可能マスからのサーチ範囲を可視化後レーダー
- [x] ボムを踏んだ時のアニメーションを考える

適宜追加してください！

**Comment by kugimasa** [comment]
待機アニメーションは以前提示した「その場歩き」はどうでしょう？

**Comment by iHiromu** [comment]
・アニメーション案
待機アニメーション：盤上の数体が動く
挟んだ時のアニメーション：挟んだ駒が間の駒の方向を向きアクション(銃でうつ、爆弾を投げるなど)を行う
挟まれた時のアニメーション：後ろに倒れるように一回転して色が変わる
駒の出現：場所のちょっと上から落ちてくる感じ
ゲーム終了時：勝ちはジャンプしたりして喜ぶ、負けは座り込んでしまう又は、下に落として勝ち色の駒だけにする

**Comment by kugimasa** [comment]
サンキュ！

**Comment by tyanio** [comment]
# アニメーション案
- 待機アニメーション
常に呼吸レベルの微振動はしてもいいかも(せんと石みたいになっちゃいそう)
そんで盤上の5%ぐらいがランダムで以下の動き:
  ‐ 足踏み
  ‐ キョロキョロ
  ‐ 銃を構える
  ‐ 準備体操
  ‐ 野営セット
みたいな？
- 挟んだ時のアニメーション
挟む駒が挟まれた駒に対して、
  ‐ 銃撃
