### ISSUE TITLE
DoubleEdged用にリモデリングとUnityへのインポートをする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#28]
- [x] コマを作る

  - [x] キャラをつくる

  - [x] 銃を作る

  - [x] ヘルメットを作る

  - [x] 装備品を作る

- [x] ボムを作る

- [x] キーアイテムを作る

**Comment by kugimasa** [comment]
#22  でかぶってる気がするけど一応Reviewに入れときます
- [ ] Tyanio

- [ ] Hiromu

- [ ] Yamakachu

**Comment by tyanio** [comment]
いや、リサイズとかそういうのをしてもらおうと思ってたから別に被ってはないよ
全部使えるサイズにしてくれた？

**Comment by kugimasa** [comment]
@tyanio なるほどね！まだUnityの3D Sceneには移してませぬ...
移したらまたレビューにぶっ込みマス
