### ISSUE TITLE
CPUを改善する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#30]
CPU云々ではなくあくまでこのゲームで勝ちに行く個人的思考ですが、これが実装できれば人間味は増すのではないかと思うので挙げていきます

- [x] BOXを取りに行くようにする

- [x] Fireを使えるようにする

- [x] 勝利確定時かつキーアイテムの場所が認知できるときにキーアイテムを取りに行くようにする

- [x] 角が取れるなら角を取る

- [x] ~点差が大きい場合は点差を埋めようとする~

- [x] ボムの周りにマスを埋めるようにする

- [x] ~キーアイテムから2マス離れているマスをとるようにする(キーアイテムがとりやすくなる)~

あと#90 の改善案から

- [x] 遅延を増やす(#96 の進捗を見ながらこれはアニメーション代理で！)

**Comment by tyanio** [comment]
この思考はなんで？って思ったら言ってください！

**Comment by kugimasa** [comment]
## 現在１個目の「アイテムがあったら取りに行く」を実装中です.

CPU.csからBombのロケーションにアクセスするために, Board.csのBombsLocationListを以下のように変更しています.
`public List<Vector2> BombsLocationList = new List<Vector2>();`
publicにしたからかわかりませんが, ボムの初期化(初期いちにハザードが配置された)がうまくいかない例がありました. (Slack参照)

コードとしては以下のようにfor文で回しています.
ただ今のコードだと, 一個取った時点で無限ループに陥ります... 😭 
```C#:CPU.cs
        //ランダムでマスを選択
        int index = Random.Range(0, CanPlaceList.Count);
        //ハザードがあれば取る
        for(int i = 0; i < CanPlaceList.Count; i++)
        {
          for(int j = 0; j < bs.BombsLocationList.Count; j++)
          {
              if(bs.BombsLocationList[j] == CanPlaceList[i])
              {
                  index = i;
              }
          }
        }
```
` bs.BombsLocationList.Count`が悪さしていると思うのですが...
というか悪さしてます 🙄

**Comment by kugimasa** [comment]
## 実は「BOXを取りに行くようにする」ではなかった...
今日気づいたんですが☝️で実装したものは「BOXがあれば取りに行く」ではなく, 
「BOMBがあれば取りに行く」になっていました...。
原因としては, BombsLocationListをそのまま参照していたため...
一度BOXListなるものを設けることにします.

**Comment by kugimasa** [comment]
リファクタ前のものなので一度チェック外します

**Comment by kugimasa** [comment]
# Boxを取りに行くようにする✔️
CPUSystem に以下のメソッドを加えました!
``` C# 
    bool CPUCanGetItem(int i)
    {
        for (int j = 0; j < doubleEdgedSystem.boxesLocationList.Count; j++)
        {
            if (othelloSystem.canPlaceCellLocationList[i] == doubleEdgedSystem.boxesLocationList[j])
            {
                return true;
            }
        }
        return false;
    }
```
[リファクタ] boxesLocationList -> itemsLocationList　の方がいい??
Boxが空いてる場合もboxesLocationListにはItemの位置が格納されるのでitemLocationListの方がわかりやすい気がしました

**Comment by kugimasa** [comment]
# 勝利 勝利確定時かつキーアイテムの場所が認知できるときにキーアイテムを取りに行くようにする ✔️
