### ISSUE TITLE
チュートリアルを作る

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#31]
# 15thSprint
- 新システムに対応したチュートリアルをつくる
---
- [x] デザイン案を描く

- [x] ~ゲームシーンを引っ張ってくる~
ゲームシーンをそのまま使います

- [x] チュートリアルでのターンの流れを実装する

- [x] チュートリアルでの画面の遷移を実装する

- [x] チュートリアル用のポップアップを作る

- [x] #35 よりチュートリアル説明文を打ち込む

- [x] ~ビルドしてテストする~
リリースにて確認します

**Comment by tyanio** [comment]
# モックアップ
https://prottapp.com/p/dfafea

**Comment by tyanio** [comment]
# デザイン案
あくまでシーンの一つの案で、ポップアップなどが画像として用意できないのでモックアップ見てください
![13_reversitutorialbase](https://user-images.githubusercontent.com/19584781/58139431-8cfe3a80-7c75-11e9-9c7c-8356590b413a.png)

**Comment by Yamakatsu63** [comment]
# 各スクリプトの大まかな役割

## TutorialManager.cs
チュートリアルの全体の流れを管理する．
ターンの進行，tutorialCanvasのアクティブ・非アクティブの操作，CPUバックエンドなどを行う．
## TutorialContents.cs
tutorialCanvasに表示されるテキストや画像を管理する．
TutorialManagerから指定されたTutorialMenuによって表示するテキストと画像のリストを変更する．
## TutorialControllButton.cs
tutorialCanvas内のボタンの処理を管理する．

**Comment by kugimasa** [comment]
現在確認できているバグです。
- [ ] チュートリアル中に盤を動かせてしまう。
- [ ] CPUが設置したマスが飛んだ場所にある

**Comment by kugimasa** [comment]
現状として見つかっているチュートリアル時のバグは改善しました。

**Comment by kugimasa** [comment]
**チュートリアルの文章について**
ざっくりですが、自分の中で考えてるアイディアとして、
案内役のキャラクターに喋らせる形のチュートリアルにしたいと思っています。
後ほどフロー図をIssueにあげたいと思います。
チームのみなさんの意見と、
PO(@tyanio)にはコンセプトとして合っているか意見をいただきたいです。

**Comment by kugimasa** [comment]
[このFigmaのリンク](https://www.figma.com/file/qaKdPDbLGBq70r9orNDSyD/Tutorial?node-id=0%3A1)から見ることができます！
見るだけならログインは不要です🙆‍♂️

**Comment by kugimasa** [comment]
チュートリアルのスタイルはこのままでいきたいけど、
ルール変更が入るならチュートリアルそのものは変更が必要です。
ただ、優先度はオンライン実装や新システム実装後の方が良いかと思います

**Comment by kugimasa** [comment]
# バグ
* 手順を指定する

**Comment by tyanio** [comment]
# バグ
Surrenderすると負けてしまうのでHomeに返すだけにした
