### ISSUE TITLE
アルファテスト版をリリースする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#44]
- [ ] Apple Storeにアルファテストリリースする

- [ ] Google Playにアルファテストリリースする

  - [x] ~apkファイル~をデバッグモードからリリースモードに変える
  aabファイルに変更

**Comment by tyanio** [comment]
# GooglePlayStoreでのアプリの署名
現状の状態ではAndroのビルドはデバッグモードであり、リリースするためにはリリースモードとして署名しなくてはいけないみたいです
調べ中…
https://developer.android.com/studio/publish/app-signing

**Comment by kugimasa** [comment]
# Apple Storeのアルファリリース
テストフライトなるものがあるらしく, 内部テスト, 外部テストができるみたいです.
アルファリリース段階なら内部テストかな...??
https://developer.apple.com/jp/testflight/

**Comment by tyanio** [comment]
# GooglePlayStoreでのリリースについての問題
GooglePlayStoreでのリリースは2019年以降8月1日以降はすべてのリリースがGooglePlayの64ビット要件に準拠してないとリリースできないようです…！！
今のUnityProjectは32ビットなので至急改善したいのですが、64ビットにするために必要なAndroid NDKが2.6GBと激重のためみんなのビルド環境をどうしようか考え中です…

**Comment by kugimasa** [comment]
https://github.com/cammelworks/doubleEdged/issues/44#issuecomment-508459952
Androidビルドを行わない自分の環境では気にしなくても大丈夫な問題ですか？

**Comment by tyanio** [comment]
# GooglePlayStoreアルファテスト！
審査待ちです！とりあえず自分だけでやっております...
