### ISSUE TITLE
エフェクトを作って表示させる

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#47]
- [x] ~レーダーエフェクトを作る~

- [x] 砲撃エフェクトを作る

- [x] 地雷の爆発エフェクトを作る

   - [x] 爆発時の煙(キノコ雲みたいな)
　
- [x] 銃を撃つエフェクトを作る

   - [x] 他のアプリなどを調べて案を考える
　
- [x] リファクタを終える

**Comment by kugimasa** [comment]
銃を撃つアニメーションについて
今の状態だとアニメーションがわかりづらい。
動いているけど言われないとわからない状態

**Comment by tyanio** [comment]
# 無料素材
http://baba-s.hatenablog.com/entry/2019/05/08/090000
使えるかも？

**Comment by kugimasa** [comment]
エフェクトは真上の視点からでも, その他の視点からでも見えるようなものにしたい。
レーダーなら今の円から球に??

**Comment by iHiromu** [comment]
・爆発時のエフェクトについて
https://youtu.be/G-D5ShhyS58
このリンクの0:24あたりの爆発(きのこあり？)を入れられたらなと考え中

・銃を撃つエフェクトについて
銃を撃ったというのをわかりやすくするために撃った時の銃口を少し光らせればいいと思って
https://assetstore.unity.com/packages/vfx/particles/war-fx-5669
のようなエフェクトを考え中
すでにあるアニメーションにどうやって加えるのかは今調べ中

**Comment by kugimasa** [comment]
・砲撃エフェクトについて
煙は出ます
砲台から玉は出ません
砲台は回転しません
