### ISSUE TITLE
基本的なオセロゲームの作り直しをする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#54]
# 15thSprintのデバッグ
- 相手のターンが終わって、次に自分が置ける緑のマテリアルが出るよりも先における場所をタップするとそれ以降緑のマテリアルが残ってしまう

- CPUがパスすると紫色のマテリアルが残ってしまう
---
- [x] パッケージをインポートする

- [x] 勝敗結果を出力する

**Comment by tyanio** [comment]
# バグ確認しました
相手のターンが終わって、次に自分が置ける緑のマテリアルが出るよりも先における場所をタップするとそれ以降緑のマテリアルが残ってしまう

**Comment by tyanio** [comment]
# バグ確認しました
CPUがパスすると紫色のマテリアルが残ってしまう

**Comment by Yamakatsu63** [comment]
セルがハイライトされる前にタップしても以降残らないようになりました。
CPUがパスをすると次のターンに紫色のセルが表示されないようになりました。
