### ISSUE TITLE
DoubleEdgedのゲームシステムに沿った開発をする

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#7]
- [x] ボムの仕様を実装する

- [x] 地雷とボムの初期配置の確率式を考える

- [x] ゲーム開始時の地雷探知機システムを実装する

- [x] ユーザーが使う地雷探知機システムを実装する

**Comment by Yamakatsu63** [comment]
- [ ] Kugi

- [ ] Tyanio

- [ ] Inami
