### ISSUE TITLE
FireBaseを導入する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#72]
- [x] FirebaseAnalyticsを導入する

- [ ] FirebaseAuthenticationを導入する

- [ ] FireBaseのほかの機能を追加する(変更してください！)

- [ ] オートログイン機能を実装する

**Comment by Yamakatsu63** [comment]
# Firebase導入方法

https://firebase.google.com/docs/unity/setup?hl=ja

**Comment by tyanio** [comment]
# Firebase沼
## Firebase(Analytics)を入れて共有すると起こるエラーについて
![2019-07-09](https://user-images.githubusercontent.com/19584781/60942033-164bf800-a31c-11e9-8d79-d5be08fb701d.png)
- Precompileエラー
何のエラーか正直自分はよくわかってないですが、画像の上丸のところのPlugins>iOSの二つのファイルのPlatformSettingsのOSのところをAnyOSからOSXにすると直ります
- MisssingMethodエラー
我々は.Net4.xを使っているので画像の下丸のところのParse>PluginsにあるUnity.CompatとUnity.Tasksを消してあげると消えるようです

**Comment by kugimasa** [comment]
https://github.com/cammelworks/doubleEdged/issues/72#issuecomment-509910692
![スクリーンショット 2019-07-11 11 03 09](https://user-images.githubusercontent.com/40158101/61017116-03ddc700-a3cd-11e9-9778-d98123e16fdd.png)
Mac環境
* Precompileエラー
Plugins直下の二つのファイルのPlatformSettingsをAnyOS->Windowsに変更するとMac環境でのエラーが消えました

ただ別のエラーが出ています...
* EntryPointNotFoundExceptionエラー

**Comment by kugimasa** [comment]
![スクリーンショット 2019-07-15 10 05 36](https://user-images.githubusercontent.com/40158101/61191911-c178fa80-a6ea-11e9-8541-644e9da35fe1.png)
![スクリーンショット 2019-07-15 10 06 07](https://user-images.githubusercontent.com/40158101/61191912-c178fa80-a6ea-11e9-980c-5467a6d9d9d6.png)
Mac環境
・ EntryPointNotFoundExceptionエラー
Google開発者サービスの要件確認でのエラーだったみたいです
現在githubでは共有されてしまうので, 共有をなくすかビルド時に外すかして対応したいと思います

**Comment by tyanio** [comment]
どうやらFirebase関連のファイルがちゃんとGitHubに共有されていないみたいです
自分の手元には今のところignoreされている.mdbファイルがあり、また他にもいろいろ原因はありそうです
gitignoreファイルを編集中ですがうまいこと行きません…

**Comment by Yamakatsu63** [comment]
unityでFirebaseを使っているプロジェクトのgithubです．
このサイトのgitignoreが参考になるかも...
https://github.com/google/mechahamster/blob/master/.gitignore
