### ISSUE TITLE
盤のマスは 8x8 or 10x10？

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#85]
実際にビルドして遊んでみたけど, 10x10だとやっぱりプレイ時間が長くなってしまうのが気になりました.

8x8だとゲームがサクッと終わりすぎてしまうことを懸念してたけど, 一試合一試合のプレイ時間にバラツキがあるほうが再戦したくなる意欲も湧く気がしました

**Comment by tyanio** [comment]
ゲーム時間がサクっと終わるほうがこの忙しい現代に空き時間でやるゲームとしてはあってると思う
広告ももっとみてもらえるし俺も8x8のほうがいいと思ったな()

**Comment by tyanio** [comment]
#90 参照！8x8になりました！
