### ISSUE TITLE
ボムを踏んだときのマスが視覚的に置けないとわかるようにする

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#86]
今のところ, 画像の赤丸がCanNotPlaceCellになってます
![](https://user-images.githubusercontent.com/40158101/57176409-996f4e80-6e92-11e9-8db9-c3ea51c56945.png)

## 今までCanNotPlaceCellは薄茶色のマテリアルがついた正方形の板でした
　改善案としてマテリアルを ❌ のテクスチャに置き換える結論に至りました.
- [x] CanNotPlaceCellのマテリアルを❌ に変える

**Comment by tyanio** [comment]
爆弾で地面が割れたよう感じになるとか、もしくは炎とか？

**Comment by daigofuji0907** [comment]
ラフにアイデア考えました。
![iOS の画像 (1)](https://user-images.githubusercontent.com/49432948/57662184-28196380-7629-11e9-8ada-4f4a643609f5.jpg)

**Comment by tyanio** [comment]
煙やひび割れ程度でコマが置けなくなるっていうのはあんまり理解されへんかもしれないかもなぁ

**Comment by tyanio** [comment]
今スプリントはバッテンで実装します

**Comment by tyanio** [comment]
![batsu](https://user-images.githubusercontent.com/19584781/57859700-6e8bdf80-782e-11e9-9db5-74a8f0bb56f7.png)

**Comment by kugimasa** [comment]
## 実装結果
Unityへ実装した結果を以下に示します.

斜め上からの視点
![スクリーンショット 2019-05-16 23 53 54](https://user-images.githubusercontent.com/40158101/57864346-aeef5b80-7836-11e9-9073-ff4ef694287b.png )
真上からの視点
![スクリーンショット 2019-05-16 23 53 51](https://user-images.githubusercontent.com/40158101/57864347-af87f200-7836-11e9-9945-2c9cf30e312c.png)
