### ISSUE TITLE
ロゴを改善する

### ISSUE THREAD

**Issue by daigofuji0907** [cammelworks/doubleEdged#88]
#33 参照

- [x] ロゴ案を作る

- [x] ロゴ案の下書きを書く

- [x] ロゴを清書する

- [x]  スクリーンやシャドウを書き入れる

- [x] 成果物として共有する
こんな感じになりました↓

![doubleedged_new_logo_1](https://user-images.githubusercontent.com/49432948/59157317-a3b0e800-8ae3-11e9-9b75-1b4d9eaa171a.png)

- [x] GIMPについてまとめる
以下にまとめています

**Comment by daigofuji0907** [comment]
GIMPについて
- 只今作成中・・・

**Comment by tyanio** [comment]
こんなん使えるかも、まだはっきり見た訳じゃないけどロゴに特化したツールもあるっぽいから探してみてもエエかもね
https://www.canva.com

**Comment by daigofuji0907** [comment]
# 作成するにあたって
今回作っている間に思ったことを書いておく
****
- 好みの画像で下書きする
適当に見つけた画像をインポートして、少し透過するだけ。
左右反転拡大縮小回転できるから、構図を考えるときにも使えた。
****
- 線を均一にする
線の太い細いで画像の中の重みが変わってくる。
→強調するなら線を太くしてもいいかも？
ペン先の太さを固定しても意味なし。
解決策
→どんな太さでもいいのでまず描く
　色を塗りつぶし、選択する
　選択範囲の縮小で中の色を塗ってしまう。
完成間近に発見。
****
- 画像サイズは大きくする
画像サイズが小さいと、不便。
拡大すると粗くなるなど。
元から大きめのサイズで描く。
使うべきは、拡大ではなく縮小。
****
