### ISSUE TITLE
？先攻、後攻の選択ボタンの色をどうしましょう？

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/doubleEdged#89]
いま先攻、後攻の選択ボタンは緑になってるけど、
先攻(黒)、後攻(白)にした方が良いと感じました。

**Comment by tyanio** [comment]
黒駒の画像とテキストの先攻、白駒の画像とテキストの後攻をボタンの中で表示してあげたほうが分かりやすい気もする

**Comment by daigofuji0907** [comment]
こんな感じかな？
![iOS の画像 (2)](https://user-images.githubusercontent.com/49432948/57664649-02458c00-7634-11e9-9691-3c1f1efb675d.jpg)

**Comment by tyanio** [comment]
そう！個人的にはコマが左にある方がいい気はする

**Comment by daigofuji0907** [comment]
なるべくキャラがボタンからはみ出すぎないようにする
キャラは左側右向き

**Comment by daigofuji0907** [comment]
黒駒はこんな感じです
![黒駒１](https://user-images.githubusercontent.com/49432948/58140496-727a9000-7c7a-11e9-8e50-c8ba41af388d.png)
![黒駒２](https://user-images.githubusercontent.com/49432948/58140498-75758080-7c7a-11e9-9442-560cd0911ffd.png)
