### ISSUE TITLE
ゲームシーンの効果音を付ける

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#95]
#29 参照！下以外にもアニメーションから必要そうなSEを考えて付けていってください！

- [x] 挟んだ際の発砲SEを付ける

- [x] ボムを踏んだ際の爆発SEを付ける

- [x] 砲撃音を付ける

- [x] コマの出現時の着地音を付ける

- [x] 倒れた時の着地音をつける

**Comment by tyanio** [comment]
# SEをつけるためには
どうやらアニメーションに直にSEをつけるためにはインポートするタイミングで設定してあげないといけないそうです…
アニメーションの元ファイルがあるのかないのか、あったとしてどこにあるのか自分にはよくわからんので教えてくださいな
https://qiita.com/yun_T/items/58e77d3396ded286affc
https://gametukurikata.com/basic/animationevent
https://criware.info/adx2forunity-animationtrigger/

**Comment by kugimasa** [comment]
登場と倒れる音も必要だと思った

fireボタンの音は??

**Comment by kugimasa** [comment]
# SEとアニメーションの対応づけ
scriptとAnimatorとの連動で(おそらく)いけるよ！

まずはscriptを用意.([プログラム側で変数に効果音を格納して再生](https://increment-log.com/unity-sound-se-play/)を参照)
![スクリーンショット 2019-05-17 22 07 22](https://user-images.githubusercontent.com/40158101/57930686-98f2a100-78f1-11e9-91fb-fe1982193213.png)
```c#:appearSound.cs
using UnityEngine;

public class appearSound : StateMachineBehaviour
{
    // OnStateEnter is called when a transition starts and the state machine starts to evaluate this state
    //override public void OnStateEnter(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    //{
    //    ココのコメントアウトを外してリンクのように記述
    //}

    // OnStateUpdate is called on each Update frame between OnStateEnter and OnStateExit callbacks
    //override public void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    //{
    //    
    //}

    // OnStateExit is called when a transition ends and the state machine finishes evaluating this state
    //override public void OnStateExit(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    //{
    //    
    //}

    // OnStateMove is called right after Animator.OnAnimatorMove()
    //override public void OnStateMove(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    //{
    //    // Implement code that processes and affects root motion
    //}

    // OnStateIK is called right after Animator.OnAnimatorIK()
    //override public void OnStateIK(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    //{
    //    // Implement code that sets up animation IK (inverse kinematics)
    //}
}

```

**Comment by tyanio** [comment]
これはアニメーションの任意の時間(もしくは開始からの時間とか)をとってこれるの？

**Comment by tyanio** [comment]
テスト

**Comment by tyanio** [comment]
テスト

**Comment by tyanio** [comment]
テスト

**Comment by tyanio** [comment]
これはアニメーションの任意の時間(もしくは開始からの時間とか)をとってこれるの？

**Comment by kugimasa** [comment]
引数に秒数指定できると思う
変数設けてとかで任意のタイミングでもできるし

**Comment by tyanio** [comment]
スクリプトにパプリックでAudioSourceのフィールド変数作ってあげて、そこにインスペクターからSEファイルをぶち込んだら再生できそうなのは理解できた
https://increment-log.com/unity-sound-se-play/

しかし、Unity上でアニメーションをどうやって確認するのか知ってたら教えて欲しい、調べてもあんま上手いこと見つからんのよね
アニメーション関連のリファレンスもよく分かってないけど、兎にも角にもアニメーションを確認せんことにはSEもつけられぬぅ

**Comment by kugimasa** [comment]
Animation選んでInspectorから再生できるよ！
![PlayAnimation](https://user-images.githubusercontent.com/40158101/57981621-bc922480-7a74-11e9-8a2b-0d5f43a6c497.png)

**Comment by tyanio** [comment]
# AnimationEventでSEを付ける
(家のデスクトップのスクショ機能が逝ってて画像つかえぬ、申し訳ない)  
Animationのウィンドウに「add event」ってボタンがあってそこで任意のフレームにイベントを作れます。
そのイベントを選んでInspectorから呼び出したい関数**名**(ここで沼った笑、()つけてただけで時間食った)をFunctionのところに入力  
呼び出したい関数があるスクリプトは実際にAnimationが動くGameObjectにつけないとだめです。

詳しくは↓
https://qiita.com/yun_T/items/58e77d3396ded286affc
https://docs.unity3d.com/jp/current/Manual/animeditor-AnimationEvents.html
https://gametukurikata.com/basic/animationevent
