### ISSUE TITLE
LoadSceneを作る

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#97]
- [x] デザイン案を描く

- [x] 白駒アニメーションを描く

- [x] どうやって実装するか調べる(そもそもシーンを用意するのか)

- [x] モックアップからシーン間の遷移を実装する

- [x] 上のデザインに沿って実装する

- [x] ビルドしてテストする
  
  - [x] フォントサイズのバグを修正する
　
- [x] リファクタを終える

**Comment by tyanio** [comment]
# コマアニメーション案
https://www.youtube.com/watch?v=Ag5WBoXm4FA

**Comment by tyanio** [comment]
![6_loadtemplate](https://user-images.githubusercontent.com/19584781/58139186-a652b700-7c74-11e9-8db7-b2cc94077bd0.png)

**Comment by tyanio** [comment]
# モックアップ
https://prottapp.com/p/dfafea

**Comment by tyanio** [comment]
# UnityにGifAnimationを挿入する方法
http://baba-s.hatenablog.com/entry/2017/12/30/230100

**Comment by tyanio** [comment]
# Load画面の実装の方法
Load画面用のCanvasを用意してロードの際に読み込むようにしています
裏のシステムに関しては割と煩雑なのでURLへ
https://gametukurikata.com/program/nowloading

**Comment by tyanio** [comment]
ビルドは調子よくないですねぇ…！
![Screenshot_20190605-155937](https://user-images.githubusercontent.com/19584781/58936583-0ab06300-87ab-11e9-828a-aa647870688b.png)

**Comment by daigofuji0907** [comment]
![ロードシーン＿白駒](https://user-images.githubusercontent.com/49432948/59166483-2463f880-8b65-11e9-8189-6844266823e3.gif)

GIF画像の残像を消すことはできましたが、画像がおかしくなります
もうちょっと調べて直します

**Comment by daigofuji0907** [comment]
![iOS のファイル](https://user-images.githubusercontent.com/49432948/59889579-fbb2ed00-9407-11e9-93db-d07e1b9e6f17.gif)
GIF画像できました！

**Comment by tyanio** [comment]
# 2DAnimationの実装方法
結局UnityはgifAnimationは対応していないので上のリンクにあるものもgifファイルの各フレームをばらしてテクスチャ化してからコマ送りにするっていう処理をまとめたパッケージでした
大吾申し訳ない…！

今回の場合そもそも4コマしかないので以下のリンクの方法で実装しました
http://befool-inc.github.io/blog/2013/05/22/unity-study-05-enable-animated-gif/
https://qiita.com/amano-kiyoyuki/items/2be43cef0079798b28b5
ただ上のサイトのGUITextureは古いのでGetComponent<RawImage>()で代用しています

**Comment by tyanio** [comment]
# フォントサイズのBest fitについて
動的なテキストにBestFitにチェックをつけてしまっていたのでテキストが変わるたびにフォントのサイズが変わっていたのでそのバグを修正しました
