### ISSUE TITLE
？ゲームシーンでのカメラの仕様を結局どうしましょう？

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#98]
今現状はカメラの仕様は切り替えボタンが置いてあってそこのカメラで前からの方向だけ確認できるって感じです

しかしゲームシステムの改善によりカメラの自由位置から盤の座標を取っては来られそうなので、改めて3D空間の上手な使い方としてのカメラ案を出してもらいたいです！

**Comment by tyanio** [comment]
# Tyani
自分はまずボタンなどは用意せずに、2本指スワイプやピンチアウトなどでカメラを盤を中心とした半球状の任意の空間にカメラを移動させたいと思います！
せっかくモデルを作ったのでいっぱい見せたい！

その後でカメラ固定ボタン、もしくは1タップで完全上視点に戻される感じはどうでしょう？
ちなみにコマを置くときは完全上視点限定でマスに1タップで置きます

また完全上視点でないときはなんらかの方法で認知させるようにもします！

**Comment by kugimasa** [comment]
# kugi
カメラ操作
   * 視点移動：フリックや指でのスライド
   * ズーム : ピンチアウト・ピンチイン
コマ操作

**Comment by Yamakatsu63** [comment]
# Yamaguchi

3D空間での視点移動だからPCのトラックパッドみたいな感じで移動できたらいいと思う．

どの視点からでもコマを置けるようにした方がユーザの要求にあってると思う．

**Comment by iHiromu** [comment]
遅くなりました
トラックパットみたいに動かせるのいいと思う、あとすぐ真上に戻るボタンも欲しいと思います

**Comment by daigofuji0907** [comment]
大変遅くなってしまいごめんなさい！
- ちゃにおのいってた半球状をカメラが移動していくイメージで、ズーム機能ありが良いと思います
- 縦画面でやるのであれば、トラックパッドよりも指でのスワイプが良いと思います
- どのカメラ角度であっても、駒を置ける方がユーザに喜ばれる気がします
- 真上に戻れるボタンは、必要だと思います

**Comment by tyanio** [comment]
#Touch(Unity Reference)
https://docs.unity3d.com/ja/current/ScriptReference/Touch.html

**Comment by tyanio** [comment]
# まとめ
- カメラは任意の半球状を動かせる
- 視点移動：一本指のスワイプ
- ズーム：ピンチアウト、ピンチイン
- 真上に戻るボタンを用意する
- どの視点でもコマは置ける
