### ISSUE TITLE
カメラの自由視点を実装する

### ISSUE THREAD

**Issue by tyanio** [cammelworks/doubleEdged#99]
#98 参照！

- [x] スワイプでのカメラ移動を実装する

- [x] ~ピンチアウト・インでのカメラズームを実装する~

- [x] カメラを真上に戻すボタンを実装する

**Comment by Yamakatsu63** [comment]
# 役に立ちそうなサイト
- unityでスワイプの実装
https://qiita.com/engineer_Intern/items/8f01f280905af6a03b3f

**Comment by Yamakatsu63** [comment]
## カメラの平行移動
カメラを平行移動するMainCamera.csを[unityでスワイプの実装](https://qiita.com/engineer_Intern/items/8f01f280905af6a03b3f)をするサイトを参考に作成しました．

## 異なるプラットフォームでの共通タッチ処理
unityのPCテストプレイでのクリックはデフォルトのTouchクラスでは認識されないため，[unityで異なるプラットフォームでの共通タッチ処理を実装](https://qiita.com/tempura/items/4a5482ff6247ec8873df)を参考にAppUtil.csを作成しました．
AppUtil.csで各プラットフォームでのクリック・タッチ処理を実装して，それをほかのクラスで使うようにしてください．

**Comment by tyanio** [comment]
![DSC_1808](https://user-images.githubusercontent.com/19584781/58138531-91285900-7c71-11e9-9243-2ffd8623ba30.JPG)
